IF
	AreaCheck("L#AF07")
	!Allegiance("L#AFDRA",ENEMY)
	!Dead("L#AFDRA")
	See("L#AFDRA")
	InParty("C0Aura")
	InMyArea(Player1)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	Global("C0AuraWhinHillDragonTalk","GLOBAL",0)
THEN
  RESPONSE #100
	SetInterrupt(FALSE)
	Wait(2)
	SetGlobal("C0AuraWhinHillDragonTalk","GLOBAL",1)
	ActionOverride("L#AFDRA",StartDialogNoSet(Player1))
END