IF
	Global("C0AuraBegin","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("C0AuraBegin","GLOBAL",4)
		StartCutSceneMode()
		CutSceneId(Player1)
		ActionOverride("C0aura",MakeGlobal())
		FadeToColor([30.0],0)
		Wait(1)
		FadeFromColor([30.0],0)
		MoveViewObject("c0aura",INSTANT)  // Aura
		CreateCreature("cutspy",[500.500],S)  // No such index
		Wait(4)
		ActionOverride("C0aura",StartDialogNoSet(Player1))
		Continue()
END

